[package]
name = "tak-rs"
version = "0.1.0"
authors = ["Matt Wismer <mattwis86@gmail.com>"]
repository = "https://github.com/MattWis/tak-rs.git"
homepage = "https://github.com/MattWis/tak-rs.git"
license = "MIT"
readme = "Readme.md"
description = "Implementation of Tak (from the Kingkiller Chronicles)"
